version: '3.8'

services:

  test_db:
    container_name: test_database
    image: postgres:15.1
    environment:
      - POSTGRES_DB=terra
      - POSTGRES_USER=vedaka1
      - POSTGRES_PASSWORD=135790qW
    ports:
      - 5432:5432

  backend:
    depends_on:
      - test_db
    container_name: backend
    build: ./services/backend
    ports:
      - 5000:5000
    volumes:
      - ./services/backend:/app
    command: pytest -s
