version: '3.8'

services:

  backend:
    depends_on:
      - db
    container_name: backend
    network_mode: "host"
    build: ./services/backend
    ports:
      - 5000:5000
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --port 5000

  nginx-terra:
    container_name: nginx-terra
    network_mode: "host"
    build:
      context: ./services/frontend
      dockerfile: ./Dockerfile 
    ports:
      - 8080:80

  db:
    container_name: database
    network_mode: "host"
    image: postgres:15.1
    env_file:
      - ./services/backend/.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
