"""fix friends table

Revision ID: c7191e2284b7
Revises: f3b724cbcbf3
Create Date: 2024-02-19 20:00:26.057693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7191e2284b7'
down_revision: Union[str, None] = 'f3b724cbcbf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_friends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('friend_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['fastapi.user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['fastapi.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='fastapi'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_friends', schema='fastapi')
    # ### end Alembic commands ###
