"""empty message

Revision ID: cf6a7822d580
Revises: 0935e5c1ad24
Create Date: 2024-02-19 21:56:07.969213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf6a7822d580'
down_revision: Union[str, None] = '0935e5c1ad24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_to_user',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('friend_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['friend_id'], ['fastapi.user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['fastapi.user.id'], ),
    schema='fastapi'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_user', schema='fastapi')
    # ### end Alembic commands ###
