name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    - name: Prepare Database
      shell: bash
      run: docker run --name test-db -e POSTGRES_DB=terra -e POSTGRES_USER=vedaka1 -e POSTGRES_PASSWORD=1234qwer -d postgres:15.1
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./services/backend/requirements.txt

    - name: Run tests
      run: cd ./services/backend/ && pytest -s
